# add_remaining.py
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from properties.models import PromoteurImmobilier
from properties.models_valuation import Wilaya

# ============================================================
# قاموس الولايات
# ============================================================
wilaya_map = {
    'TIZI OUZOU': Wilaya.objects.filter(name_ar='تيزي وزو').first(),
    'ALGER': Wilaya.objects.filter(name_ar='الجزائر').first(),
    'CONSTANTINE': Wilaya.objects.filter(name_ar='قسنطينة').first(),
    'ORAN': Wilaya.objects.filter(name_ar='وهران').first(),
    'SOUK AHRAS': Wilaya.objects.filter(name_ar='سوق أهراس').first(),
    'BATNA': Wilaya.objects.filter(name_ar='باتنة').first(),
    'SETIF': Wilaya.objects.filter(name_ar='سطيف').first(),
    'TIARET': Wilaya.objects.filter(name_ar='تيارت').first(),
    'BLIDA': Wilaya.objects.filter(name_ar='البليدة').first(),
    'BOUMERDES': Wilaya.objects.filter(name_ar='بومرداس').first(),
    'RELIZANE': Wilaya.objects.filter(name_ar='غليزان').first(),
    'BEJAIA': Wilaya.objects.filter(name_ar='بجاية').first(),
    'DJELFA': Wilaya.objects.filter(name_ar='الجلفة').first(),
    'MASCARA': Wilaya.objects.filter(name_ar='معسكر').first(),
    'AIN DEFLA': Wilaya.objects.filter(name_ar='عين الدفلى').first(),
    'GUELMA': Wilaya.objects.filter(name_ar='قالمة').first(),
    'CHLEF': Wilaya.objects.filter(name_ar='الشلف').first(),
    'S.B.ABBES': Wilaya.objects.filter(name_ar='سيدي بلعباس').first(),
    'MILA': Wilaya.objects.filter(name_ar='ميلة').first(),
    'TEBESSA': Wilaya.objects.filter(name_ar='تبسة').first(),
    'OUARGLA': Wilaya.objects.filter(name_ar='ورقلة').first(),
    'TISSEMSILT': Wilaya.objects.filter(name_ar='تيسمسيلت').first(),
    'O.E.BOUAGHI': Wilaya.objects.filter(name_ar='أم البواقي').first(),
    'EL TARF': Wilaya.objects.filter(name_ar='الطارف').first(),
    'MOSTAGANEM': Wilaya.objects.filter(name_ar='مستغانم').first(),
    'BISKRA': Wilaya.objects.filter(name_ar='بسكرة').first(),
    'ADRAR': Wilaya.objects.filter(name_ar='أدرار').first(),
    'LAGHOUAT': Wilaya.objects.filter(name_ar='الأغواط').first(),
    'TOUGGOURT': Wilaya.objects.filter(name_ar='تقرت').first(),
    'EL OUED': Wilaya.objects.filter(name_ar='الوادي').first(),
    'B.B.ARRERIDJ': Wilaya.objects.filter(name_ar='برج بوعريريج').first(),
    'BOUIRA': Wilaya.objects.filter(name_ar='البويرة').first(),
    'MEDEA': Wilaya.objects.filter(name_ar='المدية').first(),
    'TLEMCEN': Wilaya.objects.filter(name_ar='تلمسان').first(),
    'M SILA': Wilaya.objects.filter(name_ar='المسيلة').first(),
}

# ============================================================
# المطورين الجدد (الأرقام من 00618 إلى 01002)
# ============================================================
new_promoteurs = [
    ("00618", "AIT AOUDIA FERHAT", "SARL NEW URBATIM CONCEPT",
     "Local N° 02 à Bord de la rue Ben Selma Ramdane, Lotissement Cité B lot D, Nouvelle Ville, Cne de Tizi Ouzou",
     "026 21 87 39", "TIZI OUZOU"),
    ("00619", "HAMMI HAMZA", "EURL CODEV CONSTRUCTION ET DEVELOPPEMENT",
     "Rue Lakhdar Menaa, Cité 19+2 logts Bt c AP A, Cne de Ben Aknoun", "021 94 64 60", "ALGER"),
    ("00620", "ALI KHODJA REDHA", "SARL NEXT ART", "Rue Maddaoui Boudjemaa N°57 Local N°02, Cne de Constantine",
     "031 88 44 44", "CONSTANTINE"),
    ("00621", "ADOUANE MOHAMED", "EURL BENABED PROMOTION IMMOBILIERE",
     "Lotissement 283 N° 301 Local N°04, Cne de Bir El Djir", "040 21 56 57", "ORAN"),
    ("00622", "KANECH AZZEDINE", "KANECH AZZEDINE", "Lotissement Kouicem Abd El Hak Lot N°81, Cne de Souk Ahras",
     "037 32 42 98", "SOUK AHRAS"),
    ("00624", "BENALDJIA TOUFIK", "BENALDJIA TOUFIK", "Allées Salah Nezzar, N°24, Cne de Batna", "033 82 35 73",
     "BATNA"),
    ("00625", "DJAHNIT NOUREDDINE", "DJAHNIT NOUREDDINE",
     "Cité Hachemi 30 LSP Bt 03 Bloc 02, Section 02 Rez de chaussée, Cne de Sétif", "", "SETIF"),
    ("00626", "HADJADJ ACHOUR", "HADJADJ ACHOUR",
     "Cité 100 logts LSP Zaaroura Bt B1 Section 24 Ilot 48 Lot 43, Cne de Tiaret", "046 42 25 01", "TIARET"),
    ("00627", "TAYEBI HOCINE", "TAYEBI HOCINE", "Route El Souguer D 121 Bis N° 117, Cne de Tiaret", "046 22 13 41",
     "TIARET"),
    ("00628", "KHEDDAM ABDENNEBI", "SARL ECOBAT",
     "POS N°25 Résidence Panorama 01 Bloc F 1er étage Porte 161, Cne de Bir El Djir", "048 57 74 32", "ORAN"),
    ("00629", "AMARI ALI", "SARL DIAR EL BOUSTENE PROMOTION IMMOBILIERE",
     "Premier étage, RN N°09 centre Zaabana, Cne de Blida", "025 31 27 63", "BLIDA"),
    ("00630", "ADDOU DJAMEL", "SARL AH PROMOTION IMMOBILIERE", "N° 04 Rue Abdesselam Takarli, Cne de El Biar",
     "023 53 13 22", "ALGER"),
    ("00631", "CHEHIDA MOHAMED", "SARL ADEN PROMOTEUR",
     "Rue Dif Ellah Djilali, Avenue Tarablos Bt 03 étage 01, Cne de Oran", "045 21 99 72", "ORAN"),
    ("00632", "MERAIDIA SAMIA", "MERAIDIA SAMIA", "Lot Social N° 05, Cne de Ragouba", "037 77 62 68", "SOUK AHRAS"),
    ("00633", "BOURENDOUS ALI", "SARL PROMO IREAL", "Auto construction, Cne de Hamadi Krouma", "038 75 79 51",
     "SKIKDA"),
    ("00634", "GUERZA ABDELHAFID", "EURL GUERZA TRAVSKI", "Rue de citernes, Villa N° 01, Cne de Skikda", "030 92 13 98",
     "SKIKDA"),
    ("00635", "LARGUAT FATIHA", "EURL EPIL IMMOBILIER", "N°34 Rue Assela Hocine Lot N°05, Cne de Alger-Centre",
     "021 69 24 95", "ALGER"),
    ("00638", "SEBAIHI EL HACENE", "EURL PROVIDENTIA IMMOBILIES",
     "Cite Sidi Youcef N°22 H Villa 49 Rdc, Cne de Beni Messous", "034 12 01 26", "ALGER"),
    ("00639", "BELBAL MOKHTAR", "EURL KORTOBA POUR LA PROMOTION IMMOBILIERE",
     "Cité Kaid Ahmed, 500 logts AADL Bt 03 N° C04, Cne de Tiaret", "046 20 85 05", "TIARET"),
    ("00640", "GUEMMANE RABAH", "SARL TAPCO INGENIERIE ET ENTREPRISES", "Foaes Bt T2 Lot N°162 RDC, Cne de Boumerdes",
     "021 86 83 49", "BOUMERDES"),
    ("00641", "DJAAFAR SMAIN", "DJAAFAR SMAIN", "Cité 150 logts LSP, Bt A3 N° 02, Cne de Djidioua", "046 71 58 40",
     "RELIZANE"),
    ("00643", "MOKRANI NADIR", "MOKRANI NADIR", "Local N° 35 C 2eme étage, Route de Toudja, Cne de Oued Ghir",
     "034 23 92 23", "BEJAIA"),
    ("00644", "CHENAF MUSTAPHA", "SARL EL HADARA", "Cité Colonel Lahreche El Bachir Bt F N° 152, Cne de Djelfa",
     "040 51 30 74", "DJELFA"),
    ("00645", "CHENTOUF ABDELATIF", "CHENTOUF ABDELATIF", "Rue Promonade du Lac 2 éme étage, Cne de Tighennif",
     "045 97 10 93", "MASCARA"),
    ("00646", "BENRABAH ABDELKADER", "EURL LAMAMERI Z CONSTRUCTION ET TRAVAUX PUBLICS",
     "Projet 404 logts Bt 03, Cne de Khemis Miliana", "027 66 75 17", "AIN DEFLA"),
    ("00648", "AMRANI ABDERREZAK", "AMRANI ABDERREZAK", "Cité 500 logts (DNC) Local N°69, Cne de Guelma", "", "GUELMA"),
    ("00649", "ALLOULA SAMIR", "EURL IMMO STANDING",
     "Boulevard Emir Abdelkader, Angle Rue savoie Bt N° 45, Cne de Aïn El Turk", "", "ORAN"),
    ("00650", "GURBUZ MEHMET", "SARL EL MOUSTAKBEL INJAZ",
     "Coopérative Adnane Mustapha N°07 Local N°01 étage 02, Cne de Oran", "041 65 00 06", "ORAN"),
    ("00652", "CHORFI JAMEL", "CHORFI JAMEL", "Rue 1er Novembre 1954, Cne de Sedrata", "", "SOUK AHRAS"),
    ("00653", "MECHACHA SAYAH", "EURL MAMOU MOHAMED PROMOTION", "Taougrite centre, Cne de Taougrite", "", "CHLEF"),
    ("00654", "SADJI SASSI", "SARL SADJI IMMO", "Quatre chemains, RN N° 12, Cne de Béjaïa", "034 20 12 73", "BEJAIA"),
    ("00655", "KHEZAZNA SOUHAIL", "SARL SAMA MARINA", "Cité 42 logts Villa N° 19, Cne de El Bouni", "", "ANNABA"),
    ("00656", "BOUSSAHA NOURA", "BOUSSAHA NOURA", "Avenue Zemouli Amar, Lot N° 01 Local N°01 centre, Cne de Chihani",
     "038 69 52 99", "EL TARF"),
    ("00657", "BOUALI BADREDDINE", "EURL BOUALI BADREDDINE PROMOTION IMMOBILIERE",
     "Cité Said Hamdine Lot N° 444 Bt A 13 N° 07, Cne de Bir Mourad Raïs", "021 54 64 90", "ALGER"),
    ("00658", "HAMMACHI ZAHIR", "HAMMACHI ZAHIR",
     "Cité Lakhal Lamri, 150 logts Bt D 1er étage Partie 106 GP N° 19 Lot 55, Cne de Sétif", "036 44 85 21", "SETIF"),
    ("00659", "MANSOUR AMAR", "SARL MANSOUR ET ASSOCIES CONSTRUCTION",
     "Cité Mitidja rez de chaussée N° 02, Cne de Rouïba", "021 85 62 25", "ALGER"),
    ("00660", "BOUCHALA SALAH", "BOUCHALA SALAH", "N° 17, Rue de la Mairie, Cne de Zahana", "045 64 43 05", "MASCARA"),
    ("00661", "BALI ALI", "SARL B2L PRO", "N° 23 Cité la Madelaine, Cne de Hydra", "021 48 22 76", "ALGER"),
    ("00662", "MERGHEMI OUASSILA", "SARL BALI BUILDING", "Lot Val D'Hydra N° 03, Cne de Hydra", "021 48 22 76",
     "ALGER"),
    ("00663", "ACHOUR RACHID", "EURL KHALED TRADING COMPANY", "Local N°03, RN N°28, Cne de Belaiba", "", "M SILA"),
    ("00665", "HADDOUFI LINDA", "EURL HADDOUFI ETUDE ET REALISATION ET PROMOTION IMMOBILIERE",
     "Projet Kuraichi 02 Bt 27 N°03, Cne de Reghaïa", "021 79 37 77", "ALGER"),
    ("00668", "MOUKLI HACENE", "SARL MOUKLI PROMOTION IMMOBILIERE",
     "Local N°02 Centre commercial Moukli Hacene Centre Sidi Namane, Cne de Sidi Namane", "", "TIZI OUZOU"),
    ("00669", "BENAOUDA ABDELGHANI", "SARL PROMO AMIR", "Cité 70 Lgts LSP, Cne de Tadjenanet", "031 53 52 45", "MILA"),
    ("00670", "MALAOUI BOUBAKER", "MALAOUI BOUBAKER", "Cité Haouari Boumediane local N°04, Cne de Bir el-Ater",
     "037 44 69 10", "TEBESSA"),
    ("00671", "TABNI FERHAT", "TABNI FERHAT", "Projet 20 logts LSP Bt A Local 05 et 06, Cne de Ramdane Djamel", "",
     "SKIKDA"),
    ("00672", "GHERIB MOHAMED YACINE", "GHERIB MOHAMED YACINE", "Local N°80 RN N° 03, Cne de Touggourt", "029 64 01 22",
     "OUARGLA"),
    ("00674", "MEDDAHI MOHAMED", "EURL RIHEM PROMOTION IMMOBILIERE",
     "Cité 51 villas N° 46, Hammadia, Cne de Tissemsilt", "", "TISSEMSILT"),
    ("00675", "BOUDELLAL ABDERRAHIM", "SARL BENHADDOU PROMOTION ET CIE",
     "Cité 400 logts, Sidi Djillali D3 N° 169, Cne de Sidi Bel Abbes", "048 57 71 76", "S.B.ABBES"),
    ("00676", "SIDI ATTALLAH MOHAMED FOUAD", "EURL PROMOTION IMMOBILIERE SIDI ATTALLAH",
     "N° 03 Rue Beni Hendel, Hai Oussama 1er étage Lot N° 33, Cne de Oran", "041 24 03 38", "ORAN"),
    ("00677", "BENMERZOUG SALEM", "SARL BEN MERZOUG SALEM PROMOTION IMMOBILIERE BSP",
     "Sidi Maarouf hai 89 logts N° 32, Cne de Oran", "", "ORAN"),
    ("00678", "BOUHLAL NABILA", "SARL HBP IMMOBILIERE", "Lieu dit Trouville, RDC Lot N° 02, Cne de Aïn El Turk",
     "041 60 13 80", "ORAN"),
    ("00680", "GHARBI MOHAMED", "GHARBI MOHAMED", "Lotissement Lot N°05 Zone 02 N°04, Cne de Chettia", "027 72 02 70",
     "CHLEF"),
    ("00681", "SEGUENI NOURI", "EURL SEGFROR", "Cité Yasmine Pos 52, Résidence Ryad 87 Lgts Bt A, Cne de Sidi Chami",
     "041 67 60 44", "ORAN"),
    ("00682", "MEZGHICHE KHEIR", "MEZGHICHE KHEIR", "Derdani Route Metaouak Lotissement 34 logts, Cne de Barika",
     "033 89 23 42", "BATNA"),
    ("00683", "TOLBA HANAFI", "TOLBA HANAFI", "Lotissement Maloume Ben Aiche N°65, Cne de Meskiana", "032 47 14 52",
     "O.E.BOUAGHI"),
    ("00684", "ATTALLAH KARIM", "ATTALLAH KARIM", "Cité de la Madeleine N°18, Cne de Hydra", "023 23 05 38", "ALGER"),
    ("00686", "BOULBERDAA RACHID", "BOULBERDAA RACHID", "Cité Massinissa n°212 B, Cne de El Khroub", "031 82 94 52",
     "CONSTANTINE"),
    ("00687", "AGLI MOHAMED SAMI", "SARL TAAMIR EL DJAZAIR", "N°09 Rue les freres Ben Hafid, Cne de Hydra",
     "021 60 41 42", "ALGER"),
    ("00688", "BOUZIDI AHMED", "BOUZIDI AHMED",
     "Zone urbaine 72 logts et 36 commerces, Bt 01 Appt N° 07 1er étage, Cne de Aïn Béïda", "032 47 53 69",
     "O.E.BOUAGHI"),
    ("00689", "BELKAID ABDI LAKHDAR", "BELKAID ABDI LAKHDAR",
     "Cité Zerrouki Cheikh Ben Eddine, Cne de Sidi M'Hamed Ben Ali", "046 94 06 75", "RELIZANE"),
    ("00690", "ALLAOUA HICHAM", "ALLAOUA HICHAM", "Cité El Mostakbel N°37, Cne de Oum el Bouaghi", "032 42 76 12",
     "O.E.BOUAGHI"),
    ("00691", "CHELEF HICHEM", "SARL EL BARAKA PROMOTION IMMOBILIERE",
     "Rue 11 Décembre 1960 Section 46 Ilot N°19, Cne de Blida", "025 21 09 87", "BLIDA"),
    ("00692", "HAMZA CHERIF GHOUTI", "HAMZA CHERIF GHOUTI",
     "El Kiffane Résidence Ibn M'Saib, Bt D Rez de chaussée N° 06, Cne de Tlemcen", "043 56 40 60", "TLEMCEN"),
    ("00694", "HASROUMI NOUREDDINE", "HASROUMI NOUREDDINE", "N° 10 Rue A-N, Cité Lombarkia, Cne de Batna",
     "033 92 80 49", "BATNA"),
    ("00695", "ADJOUT AQILA", "ADJOUT AQILA", "Local N°33 Village Mezguen, Cne de Illoula Oumalou", "", "TIZI OUZOU"),
    ("00696", "BEZZALA MOHAMMED", "SNC BEZZALA ET FILS", "Route Tazoult N° 17, Cne de Batna", "", "BATNA"),
    ("00697", "BOUSSELBA RACHID", "BOUSSELBA RACHID",
     "Lotissement 19 juin deuxième Extension, Section 04 Ilot Lot 478, Cne de Guelma", "066 13 60 16", "GUELMA"),
    ("00698", "AIT AISSI RACHID", "SARL EDEN PRIM", "Village Lazib Ouamer Iheddaden, Cne de Béjaïa", "034 32 52 37",
     "BEJAIA"),
    ("00699", "MOUAICI FETHI", "MOUAICI FETHI", "Rue Senoussi Lahbib N°04, Cne de Mascara", "", "MASCARA"),
    ("00701", "EL AGRARI MOHAMMED", "EL AGRARI MOHAMMED", "Cité 146 logts LSP, route ouest de Ténès, Cne de Ténès",
     "027 45 10 99", "CHLEF"),
    ("00702", "DJOUADI AZEDDINE", "DJOUADI AZEDDINE", "Cité 260 logts Promotionnels N° 119, Cne de Guelma",
     "038 89 32 69", "GUELMA"),
    ("00703", "DAOUDI FAYCAL", "SARL PROMOTION IMMOBILIERE LABBACI OURAILLA",
     "Champ de mars lot 21, local 04, Cne de Annaba", "038 44 58 87", "ANNABA"),
    ("00705", "GHANI AMAR", "GHANI AMAR", "Cité des 70 Villas N°18, Cne de Boumerdes", "024 94 76 90", "BOUMERDES"),
    ("00707", "ZIDI YAHIA", "SARL GASMI IMMO", "Hai Khemisti Résidence Belle Vue Lot N° H1 Bt D3 N°43, Cne de Oran",
     "040 22 02 78", "ORAN"),
    ("00708", "BOUTAIEB MOSBAH", "BOUTAIEB MOSBAH",
     "Lot Slimane Amirat, Lot N° 10 Section 28 Ilot 404, Cne de Souk Ahras", "037 32 45 03", "SOUK AHRAS"),
    ("00709", "KADDOURI LARBI", "SARL ADEN PROMOTION IMMOBILIERE",
     "Slamandar Lot P20 Bloc A1 RDC part N°06, Cne de Mostaganem", "045 35 15 57", "MOSTAGANEM"),
    ("00710", "LAIB SAMIR", "SARL BOUTEL LAIB PROMOTION IMMO", "Local N° 04 C Rue la rocade Boghni, Cne de Boghni", "",
     "TIZI OUZOU"),
    ("00711", "GHERARI MOHAMED ISSAM", "GHERARI MOHAMED ISSAM",
     "Plage Rizi omar Hyppone promotion, Bt B N°103, Cne de Annaba", "", "ANNABA"),
    ("00712", "BEREKSI REGUIG SAMIR", "BEREKSI REGUIG SAMIR",
     "Cité Khaldia 01, Rue Hamoudi Houari Local 04, Cne de Oran", "041 46 28 28", "ORAN"),
    ("00713", "HASNAOUI MOHAMED KHALED", "SPA SPI HASNAOUI", "Zone industrielle, Cne de Sidi Bel Abbes", "048 77 03 17",
     "S.B.ABBES"),
    ("00714", "LAYACHI ABDELOUAHIB", "SARL ZIMOU IMMO", "N° 33 bis rue fréres Meriem, Cne de Tizi Ouzou",
     "026 12 49 06", "TIZI OUZOU"),
    ("00716", "OUKIL RACHID", "SARL ESERIT CAPITALIA", "Cité Bouscoult 02 N°92 Porte N°17, Cne de Bouzareah",
     "021 51 91 07", "ALGER"),
    ("00719", "BELAYACHI RABIE ABDELGHANI", "SARL PROMOTION IMMOBILIERE EL WASSID",
     "Salamandre, cité Lakhlouf P/27 Bt U N° 120, Cne de Mostaganem", "040 27 50 25", "MOSTAGANEM"),
    ("00720", "MEGANI ABDELHAMID", "MEGANI ABDELHAMID", "Cité 32 logts Bt A4 Bloc N° 53, Cne de Mekla", "026 30 22 96",
     "TIZI OUZOU"),
    ("00721", "VAYREDA CASADEVALL JOAQUIM", "SARL GAUDI PROMOTION", "Cité Ain Abdellah, Cne de Boumerdes",
     "024 94 31 58", "BOUMERDES"),
    ("00722", "HOCINE AREZKI", "SARL PANORAMIQUE CONSTRUCTION", "N° 01, Cité El Yasmine Kaouche, Cne de Dely Ibrahim",
     "021 37 52 65", "ALGER"),
    ("00723", "KEROUR CHOUAIB", "SARL EL HARAM PROMOTION IMMOBILIERE",
     "Bt D Semara sud group 50 logts LSP, Section 14 Ilot de propriete N° 233, Cne de El Eulma", "036 54 96 57",
     "SETIF"),
    ("00724", "MANKOUR MOHAMED EL AMINE", "EURL MANKOUR PROM",
     "POS 50 Lot B Résidence Rym Milissa Bt B Lot N°132 Local N°09, Cne de Bir El Djir", "048 47 45 95", "ORAN"),
    ("00725", "EL FERANJI MOHAMED", "EL FERANJI MOHAMED", "Ilot I 07 N° 03, Cne de Bir El Djir", "041 28 53 12",
     "ORAN"),
    ("00726", "BAMBRIK MOHAMMED YAZID", "SARL LITTORAL IMMOBILIER",
     "Hai Sidi El Houari Place de l'armée de libération nationale, Cne de Oran", "041 45 52 50", "ORAN"),
    ("00728", "HANNACHI ABDELHALIM", "SARL DAR EL IMAN PROMOTION IMMOBILIERE", "Rue el Arbi Allik N°07, Cne de Hydra",
     "", "ALGER"),
    ("00729", "NEGUEZ AHMED", "NEGUEZ AHMED", "Cité 14 logets local 08/36 Bt B, Cne de M'Sila", "035 33 87 45",
     "M SILA"),
    ("00730", "HAMACHE REZKI", "HAMACHE REZKI", "Cité Mouilha 60 LSP N°12 Local N°05, Cne de M'Sila", "", "M SILA"),
    ("00731", "DJAHNIT SEDDIK", "DJAHNIT SEDDIK", "Ilot 179 lot El Hachichia, Cne de Mezloug", "", "SETIF"),
    ("00732", "BEDRANI DJILALI", "BEDRANI DJILALI", "Cité Elamel 234 logements, Cne de Aïn Defla", "027 59 10 12",
     "AIN DEFLA"),
    ("00733", "BOUKHATEM RABAH", "SNC BOUKHATEM PROMOBAT", "Rue Mohamed Debbab, Cne de Guelma", "037 20 16 23",
     "GUELMA"),
    ("00735", "HADIDI AHCEN", "HADIDI AHCEN", "Cité plaine ouest 08 mars B, Lot N°13, Cne de Annaba", "038 43 89 98",
     "ANNABA"),
    ("00739", "MOSTEFA FARID", "MOSTEFA FARID", "Route du port Front de mer, Cne de Ténès", "027 76 01 74", "CHLEF"),
    ("00740", "BEN SMAIL DJAMEL", "BEN SMAIL DJAMEL", "Bouilef, Local N°01, Cne de Naciria", "", "BOUMERDES"),
    ("00741", "NASRI ABDELMALEK", "NASRI ABDELMALEK",
     "Cité 60 LSP pole makomades 1+2 Bt 02, rez de chaussée, Cne de Oum el Bouaghi", "032 54 10 35", "O.E.BOUAGHI"),
    ("00743", "GUELLOUH LADJEL", "GUELLOUH LADJEL", "Salamandre Bt M N° 04, Cne de Mazagran", "045 33 06 42",
     "MOSTAGANEM"),
    ("00744", "BLIDI BOUKAMEL KHALED EL OUALID", "SARL PROMOBRUX", "N°96, rue Mohamed Boudiaf, Cne de Oran",
     "041 50 13 28", "ORAN"),
    ("00747", "DEBECHE MOHAMED LAMINE", "EURL TIBLATINE CONSTRUCTION",
     "Chemin de L'Université Targa Ouzemour, Cne de Béjaïa", "034 21 52 05", "BEJAIA"),
    ("00748", "MOSTEFAOUI BRAHIM", "SARL SEVEN PILLARS", "N° 136 Bois des cars 02, Cne de Dely Ibrahim", "", "ALGER"),
    ("00749", "SAHRAOUI LYDIA", "EURL BAT", "Boulevard Colonel lamouri Abdelkader N°01, Cne de Annaba", "038 83 80 64",
     "ANNABA"),
    ("00750", "DJARDI FATEH", "DJARDI FATEH", "Hai 450 logements N° 07, Cne de Sétif", "036 83 53 77", "SETIF"),
    ("00752", "DAOUD KAMEL", "DAOUD KAMEL", "Cité 54 logts Bloc A1-A2, rez de chaussée, Cne de El Asnam",
     "026 91 02 91", "BOUIRA"),
    ("00753", "CHOUADRA YOUCEF", "CHOUADRA YOUCEF", "MGHU, Rue N° 02 Bt 02 E N° 06 rez de chaussée, Cne de Sétif",
     "036 51 17 09", "SETIF"),
    ("00754", "CHOUADRA TAREK", "CHOUADRA TAREK",
     "Cité Gaoua projet 40 logts + 24 locaux + 08 Bt A Escalier 01, Local N°03, Cne de Sétif", "036 93 86 90", "SETIF"),
    ("00755", "HAMMOU ZINE ABDERRAHMANE", "HAMMOU ZINE ABDERRAHMANE", "Rue el Issteklal N° 03, Cne de Adrar",
     "066 1 27 88", "ADRAR"),
    ("00757", "BEZZALA AHMED", "BEZZALA AHMED", "Cité Tamachite, rue Maamria Saou N° 02, Cne de Batna", "", "BATNA"),
    ("00758", "HOUHOU MOHAMED", "HOUHOU MOHAMED", "Coppérative Echahid Bou Setta, zone ouest N° 06, Cne de Biskra",
     "033 71 22 31", "BISKRA"),
    ("00760", "KHERIFI YANIS", "EURL PROMOTION IMMOBILERE KHERIFI YANIS",
     "Cité Snober, Bloc 01 Escalier 04 N°47, Cne de Guelma", "", "GUELMA"),
    ("00763", "BOUDJELAL AHMED", "BOUDJELAL AHMED", "Cité El Fellah, Cne de El Madher", "033 93 80 89", "BATNA"),
    ("00764", "BOURAS ABDESSELAM", "EURL BOURAS ABDESSELAM TRAVAUX PUBLICS", "Route Nationale N° 05, Cne de Tadjenanet",
     "", "MILA"),
    ("00765", "GHODBANE REDJEM", "GHODBANE REDJEM",
     "Groupe d'habitations individuelle 85 lots N°78, Cne de Ouled Rahmoune", "031 80 11 83", "CONSTANTINE"),
    ("00766", "DAMBRI SADEK", "EURL EL FADJR PROMOTION IMMOBILIERE",
     "Cité Gouadjelia Rabah Projet 160 Logts LSP Bt 11 Local N°185 et 186, Cne de Aïn M'lila", "031 66 50 73",
     "O.E.BOUAGHI"),
    ("00767", "RAHMANI ABDERAZAK", "EURL DAR ETTACHYID ETUDES ET REALISATION",
     "Cité 08 mai 1945 N°60 Local N°02, Cne de El Khroub", "031 96 88 48", "CONSTANTINE"),
    ("00769", "AIDLI MOHAND AREZKI", "SARL DAR NACER IMMO",
     "Sidi Ahmed avenue des martyres Melali ex route des cretes, Cne de Béjaïa", "034 21 73 71", "BEJAIA"),
    ("00770", "CHETTAH LAKHDAR", "CHETTAH LAKHDAR", "Lotissement 221 Tranche, Local N°42, Cne de Oued Athmania",
     "031 50 73 27", "MILA"),
    ("00771", "HAMADOU MOHAMED SADDEK", "EURL HAMADOU MOHAMED SADEK PROMOTION IMMOBILIERE",
     "Hai Hachemi D N° 173, Rue Saoudi Abdelkader, Cne de Sétif", "036 91 28 07", "SETIF"),
    ("00773", "BENABID RATIBA", "EURL MALAK PROMOTION IMMOBILIERE",
     "Coopérative immobilière Houammed Chahid Bouzid belayat, Lot N°03, Cne de Sétif", "036 53 81 32", "SETIF"),
    ("00776", "KENZARI MOUHSIN", "SARL KENZARI PROMO", "Cité 180 Logts, Bt 13 N° 01, Cne de Bab Ezzouar",
     "023 83 58 62", "ALGER"),
    ("00777", "SAHMOUNE MOHAMMED AMEZIANE", "SARL PRO IMMO SAHNOUNE ET FILS",
     "Village Djemaa Saharidj, Local N° 032A, Cne de Mekla", "026 37 12 65", "TIZI OUZOU"),
    ("00779", "ZEBICHE LAKHDAR", "ZEBICHE LAKHDAR", "Rue Boumnir Mouloud, La rue d'Alger Bazar fetoumi, Cne de Médéa",
     "025 78 07 91", "MEDEA"),
    ("00781", "AMOURI LAROUSSI", "SARL TAAMIR BISKRA",
     "Cité 24 logts Bt 02 Bloc 03, route de Chetma El Alia, Cne de Biskra", "033 75 41 42", "BISKRA"),
    ("00782", "ACHI SALIM", "ACHI SALIM", "Zone d'activité Kechida Lot N°60 Local N°05, Cne de Batna", "030 36 34 45",
     "BATNA"),
    ("00783", "CHETTIR SADDEK", "CHETTIR SADDEK", "Cité Dalaa rue hassouna Ramdhan N°02, Cne de Biskra", "033 54 01 72",
     "BISKRA"),
    ("00784", "GAROUI ZAHIR AMIROUICHE", "SARL BATINDRMES",
     "Cité Djamal Eddin cooperative Nour Ilot B Lot 01, Cne de Oran", "026 20 04 08", "ORAN"),
    ("00786", "SEKOUANE BACHIR", "SEKOUANE BACHIR", "Cité 200 logts, Route de sougueur Bt G N°11, Cne de Tiaret",
     "046 25 88 21", "TIARET"),
    ("00787", "KHOUILDI TAYEB", "KHOUILDI TAYEB", "Rue Zerzi Ahmed, Cne de Aflou", "029 96 74 32", "LAGHOUAT"),
    ("00789", "YAZID NASSIM", "SARL SOCIETE DE PROMOTION IMMOBILIERE HABITA CONCEPT",
     "Promotio Immobilière Emir Abdelkader Bt B N°10, Cne de Béjaïa", "034 16 25 44", "BEJAIA"),
    ("00790", "GANA KAMEL", "GANA KAMEL", "Lot Veuve Amirouche Local N°02, Cne de Tizi Ouzou", "026 20 34 57",
     "TIZI OUZOU"),
    ("00793", "REZGUI LAHCENE", "REZGUI LAHCENE", "Avenue Zeouaoui Abdelmadjid, Cne de Aïn Béïda", "", "O.E.BOUAGHI"),
    ("00794", "GASMI YACINE MAHMOUD", "EURL GASMI ARCHI PROM",
     "Sadikia gumbitta, rue Charko N° 10, 1er étage, Local N°03, Cne de Oran", "041 53 49 61", "ORAN"),
    ("00796", "RAHMOUNI SAMIR", "SARL RAHMOUNI", "Nedjma zone de dépôt 06, Lot N°12, Cne de Sidi Chami", "041 70 55 55",
     "ORAN"),
    ("00800", "ZERAR MILOUD", "EURL ABDERRAHMANE PROMOTION IMMOBILIERE", "Hai Enour Sidi Maarouf, Cne de Sidi Chami",
     "041 70 60 84", "ORAN"),
    ("00801", "BEMMOUSSAT MOURAD", "BEMMOUSSAT MOURAD",
     "N° 601, Lotissement H'bak Bouhnak Local N°01, Cne de Mansourah", "040 91 47 97", "TLEMCEN"),
    ("00804", "NASRI KAMEL", "NASRI KAMEL", "Cité 24 février 1971 Lot N°04, Cne de Sedrata", "037 37 70 47",
     "SOUK AHRAS"),
    ("00806", "OULMI SAMIR", "SARL IMMO CASTLE PROMOTION", "Cité Garidi 2 Bt 70 N°10, Cne de Kouba", "021 44 77 70",
     "ALGER"),
    ("00808", "SAHAR MOHAMED", "EURL ENTREPRISE SAHAR TRAVAUX GENERAUX", "Cité Aissat Idir N°15, Cne de Adrar",
     "049 96 36 15", "ADRAR"),
    ("00810", "LOUAHEM M SABAH ALI", "LOUAHEM M SABAH ALI", "N°06 Cité Abdelhafidh Boussouf, Cne de Constantine",
     "038 75 67 40", "CONSTANTINE"),
    ("00811", "KADA DIFALLAH", "KADA DIFALLAH", "Cité Maralez N°102, Cne de Birkhadem", "023 54 28 45", "ALGER"),
    ("00816", "KACIR FAIROUZ", "KACIR FAIROUZ",
     "Cité Thelidjane Rue Dehbi Mohammed N°12 Section 258 Ilot N°18, Cne de Sétif", "036 71 47 11", "SETIF"),
    ("00817", "BAIFOUH MOUSSA", "BAIFOUH MOUSSA", "Hai 1200/40 N°24 Bt D, Cne de Amoucha", "036 87 78 09", "SETIF"),
    ("00819", "RAMOUL MONCEF", "SARL ENNAJAH", "Hai 05 Juillet 1962, RDC, Cne de Annaba", "", "ANNABA"),
    ("00820", "MADANI MOHAMMED LARBI CHAKER", "EURL CONSTEC",
     "N°28, lotissement El Feth ( Sable Rouge ), Cne de El Biar", "021 79 29 90", "ALGER"),
    ("00821", "BOUDERBALA MILOUD", "SPA BATIGEC PROMOTION IMMOBILIERE",
     "Cité 1000 Logements LSP BT 54 Lot N°43, Cne de Bordj El Bahri", "021 51 38 50", "ALGER"),
    ("00822", "GUERROUI DJAMEL", "GUERROUI DJAMEL", "Cité 1000 logts N° 808, Cne de Guelma", "037 10 11 86", "GUELMA"),
    ("00824", "BERRACHED KAMAL", "BERRACHED KAMAL",
     "Quartier C ZHUN Sud Nouvelle Ville, local N° 01, Cne de Tizi Ouzou", "026 18 23 09", "TIZI OUZOU"),
    ("00825", "BENABDALLAH OMAR", "EURL PERLE BLANCHE MOSTAGANEM",
     "Cité 52 Logts LSP La Perle Blache Bloc G Service, Cne de Mostaganem", "045 35 12 75", "MOSTAGANEM"),
    ("00826", "ZEBICHE ALI", "SNC FRERES ZEBICHE CONSTRUCTION", "Lotissement N°55, Cne de Beni Slimane", "025 51 51 57",
     "MEDEA"),
    ("00827", "TALAMALI OMAR", "SARL SISSOU CONSTRUCTION",
     "Cite Said Hamdin 574/195 Logs Bt 41 Model D2 Sous Sole N°09, Cne de Bir Mourad Raïs", "024 91 41 79", "ALGER"),
    ("00828", "SALHI MUSTAPHA", "EURL PROMOTION IMMOBILIERE BIEN ETRE",
     "Cité Said Hamdine Lot N°384 Bt S 01 N°05, Cne de Bir Mourad Raïs", "023 59 83 13", "ALGER"),
    ("00829", "AMIRI MILOUD", "AMIRI MILOUD", "N°09 Bt 01 Bloc A 1ere étage, Résidence 16 logements, Cne de El Bouni",
     "035 59 23 21", "ANNABA"),
    ("00831", "KHORCHEF KOUIDER", "KHORCHEF KOUIDER", "Bt D le nouveau pôle urbain, Cne de Médéa", "025 78 02 71",
     "MEDEA"),
    ("00832", "LARBI SADIA", "SARL BELKHELOUAT PROMOTION", "N°16, Rue Amer Idjegouane, Cne de Boghni", "026 23 14 14",
     "TIZI OUZOU"),
    ("00833", "BENZIDANE MOHAMMED ELAMINE", "SARL SOPRI LAND PROMOTION IMMOBILIERE",
     "Cite Adiar Ward Bt C N°07 Premier Etage Adroite, Cne de Relizane", "046 76 02 81", "RELIZANE"),
    ("00834", "YAHIAOUI MEROUANE", "SARL YAKID LILISKANE",
     "Route Nationale N° 24, Promo Immob 72 logts, Cne de Boumerdes", "", "BOUMERDES"),
    ("00836", "REMILI NOUREDDINE", "REMILI NOUREDDINE", "Lotissement 213 logts Cité Bourouh, Cne de Ferdjioua",
     "031 59 63 14", "MILA"),
    ("00838", "BOUDIAF MAHIEDDINE", "EURL B CONSTRUCTION AND STEEL", "Cité Ben Omar Villa 44 B, Cne de Kouba",
     "021 28 62 84", "ALGER"),
    ("00839", "CHORFI OUAHID", "CHORFI OUAHID", "Lot N°01, Chentata Rez de chaussée Bt E N°01, Cne de Annaba",
     "038 84 12 55", "ANNABA"),
    ("00840", "MEGARI BACHIR", "SPA ASSURE IMMO", "N°07 Avenue des frères Bouadou BP N°127, Cne de Bir Mourad Raïs",
     "021 67 87 61", "ALGER"),
    ("00841", "DIABI ALI", "EURL NASSIM PROMOTION IMMOBILIERE",
     "Lieu dit Boukhadra (Bidari) N°07 Section 81, Cne de El Bouni", "", "ANNABA"),
    ("00842", "MEKIDECHE MOURAD", "SARL EL HANA CONSTRUCTION IMMOBILIERE",
     "N°02 Boulevard Decteur Tidi, 2ème étage N°205 et 206, Cne de Annaba", "", "ANNABA"),
    ("00843", "BECHEBECHE SMAIL", "EURL BECHEBECHE SMAIL POUR LA PROMOTION IMMOBILIERE",
     "Lotissement Saada Bloc B, Cne de Aïn Kercha", "", "O.E.BOUAGHI"),
    ("00844", "GUIRI YACINE", "GUIRI YACINE", "Rue El Kods, 2ème étage local N°16, Cne de Barika", "033 89 11 90",
     "BATNA"),
    ("00847", "BOUGHELMALLAH ABDELKADER", "BOUGHELMALLAH ABDELKADER",
     "Taougrit Centre 50 Logts Promotionnel, Cne de Chlef", "", "CHLEF"),
    ("00848", "BOUKERAA ABED", "BOUKERAA ABED", "Cité 90 logts N°49, Cne de Mascara", "045 73 72 31", "MASCARA"),
    ("00849", "LOUARDI TAYEB", "EURL ENTREPRISE TAYEB PROMOTION IMMOBILIERE",
     "Lotissement 8 lot A, Cité El Alia route de Chetma, Cne de Biskra", "033 51 51 97", "BISKRA"),
    ("00850", "TALBI NABIL", "SARL MARSA EL ZITOUNE TCE", "N° 01 Rue de l'avant port, Cne de Annaba", "038 86 99 87",
     "ANNABA"),
    ("00851", "TALBI BADAOUI", "EURL SGTI TALBI",
     "Nouvelle ville Ali Mendjeli, Zone d'activité N°111, Cne de El Khroub", "031 95 79 88", "CONSTANTINE"),
    ("00852", "BOURAS RACHID", "BOURAS RACHID", "Route National N° 05 Local N°06, Cne de Tadjenanet", "031 59 50 46",
     "MILA"),
    ("00853", "KACIMI MADJID", "EURL KACIMI TRAVAUX TCE", "Ait Frah, Cne de Larbaâ Nath Irathen", "026 26 27 38",
     "TIZI OUZOU"),
    ("00854", "BALOUL DJELLOUL", "BALOUL DJELLOUL", "Cité Smina Bas Deriere Actel Amriou, Cne de Béjaïa",
     "034 21 42 91", "BEJAIA"),
    ("00855", "BEN MAZOUZ TOUFIK", "BEN MAZOUZ TOUFIK",
     "Cité Kartala Lotissement Ilot N° 08, Rez de chaussée, Cne de Baba Hassen", "", "ALGER"),
    ("00857", "ZAIDAT KARIM", "ZAIDAT KARIM", "Local N°03 RDC, Village Igil Bouzal, Cne de Azazga", "", "TIZI OUZOU"),
    ("00859", "BEDJAOUI ADEL", "EURL ADIL PROMOTION PLUS", "Ilot 1114 section 01 Lot N° 28, Cne de Birkhadem", "",
     "ALGER"),
    ("00860", "BENGUERAR KARIMA", "EPE EURL PROMOTION IMMOBILIERE OUEST",
     "Complexe Immobilière El Hanaa Tidjedit, Cne de Mostaganem", "045 30 10 42", "MOSTAGANEM"),
    ("00861", "DJELLOUL DAOUD AHMED", "SARL SPID", "Coopérative El Mostakbal 02 N°97, Cne de Bir El Djir",
     "041 53 70 39", "ORAN"),
    ("00863", "BENDI OUIS NOUFEL SALIM", "EURL BENDI OUIS IMMOBILIER",
     "N°381 Coopérative Ennour 1er étage, Cne de Bir El Djir", "", "ORAN"),
    ("00864", "BENSADOK ALA EDDINE", "EURL KHEZAZNA KHALED", "Cité 900 Logts, N° 02 1er étage, Cne de El Bouni", "",
     "ANNABA"),
    ("00865", "BENMERIDJA FOUAD", "BENMERIDJA FOUAD",
     "Hay Salamandre Résidence El Ahlem Bloc 04 Lot N° 68 Local N° L 16, Cne de Mazagran", "045 33 06 42",
     "MOSTAGANEM"),
    ("00866", "CHENTOUF M'HAMED", "EURL CHENTOUF M'HAMED CONSTRUCTION", "N°06 Rue Mimouni Lahcene, Cne de Mohammadia",
     "041 74 81 98", "MASCARA"),
    ("00867", "ADDAR DJILLALI", "ADDAR DJILLALI", "Lotissement 94 section 36 Ilot 137, Cne de Bouira", "026 73 51 47",
     "BOUIRA"),
    ("00868", "HAMOUCHE SAOU", "SARL GMPAE", "Aokas Centre, Cne de Aokas", "034 38 01 69", "BEJAIA"),
    ("00869", "BOUDJEMLINE KHALIL", "SARL GLOB BAT",
     "Nouvelle ville Ain El Bey Ali Mendjeli Bt 08 N°71, Cne de El Khroub", "", "CONSTANTINE"),
    ("00873", "BAAZIZ BACHIR EDDINE", "EURL ARCHICOL", "Rue Didouche Mourad, Cne de Collo", "038 71 86 25", "SKIKDA"),
    ("00874", "BELARBI MOULAY EL HABIB", "EURL BMH PROMOTION",
     "Cité 72 logts route d'Oran, Ilot D N° 45, Cne de Mostaganem", "", "MOSTAGANEM"),
    ("00875", "DERRAR HAFID SAMIR", "SARL UNION BETON PROMOTION",
     "N°20 rue Beni Chograne, Hai El Moudjahidine, Cne de Oran", "041 41 53 91", "ORAN"),
    ("00876", "BIT CHEIKH BACHIR", "SARL IMAD PROMOTION IMMOBILIERE",
     "Hai Khemisti rue Carrula N°192 Local N°05, Cne de Bir El Djir", "041 62 22 78", "ORAN"),
    ("00877", "MERZOUG MOURAD", "MERZOUG MOURAD", "Lotissement 134 logts, zone des activités N° 374, Cne de Chetma",
     "033 74 72 59", "BISKRA"),
    ("00878", "MABROUK MALIK", "MABROUK MALIK", "Cité Chatouni, rue Souidi Abdelkrim N°03, Cne de Biskra", "",
     "BISKRA"),
    ("00879", "MELIOUH KAMEL", "MELIOUH KAMEL", "Cité 50 logts Bt 03 Local N°14, Cne de Biskra", "033 75 63 56",
     "BISKRA"),
    ("00880", "SEHAIBI FAWZI", "SEHAIBI FAWZI", "Aïn-Sefra, Cne de Nezla", "029 68 56 32", "TOUGGOURT"),
    ("00882", "DRAM ABDERRAZAK", "DRAM ABDERRAZAK", "Hai Elistiklal, Cne de Tendla", "032 16 26 80", "EL OUED"),
    ("00886", "DJERADA RACHID", "DJERADA RACHID", "Cité 112 logts Sghir Bt 02 N°02, Cne de Béjaïa", "034 20 31 91",
     "BEJAIA"),
    ("00887", "MAHI MOHAMED YACINE", "MAHI MOHAMED YACINE", "Route de Bach Djerah Lot N°08, Cne de Hussein Dey",
     "021 56 59 46", "ALGER"),
    ("00888", "AICHE BOUBAKER", "AICHE BOUBAKER", "Rue Ahmed Boumeda, centre commercial Akfadou, Cne de Béjaïa",
     "034 22 05 06", "BEJAIA"),
    ("00889", "TAGUETIOUT LOUCIF", "SARL GST PROMOTION IMMOBILIERE ET APPROVISIONNEMENT",
     "Morcellement nouvelle ville route d'Alger n° 02, Cne de Bou-Saâda", "035 53 47 16", "M SILA"),
    ("00890", "HADJADJ ALI", "EURL HILAL LITAAMIR", "03, Avenue martyr Taoug Mohamed 1942/1958, Cne de Blida",
     "025 30 01 47", "BLIDA"),
    ("00891", "AOUCHICHE IDIR", "SARL PROMOTION IMMOBILIERE FORUM DE L'UNIVERSITE",
     "Targa Ouzemour, route de l'université, Cne de Béjaïa", "034 11 70 58", "BEJAIA"),
    ("00892", "CHIBANE SAID", "SARL EL BOUNIENE EL ALI", "Ferme Djellal, route de Djaouab, Cne de Sour El Ghouzlane",
     "", "BOUIRA"),
    ("00893", "QIN JIAN JUN", "EURL GAEA CHINA CONSTRUCTION LIMITED COMPANY",
     "N°110 Rote Frai Vallon 1er étage, Cne de Bouzareah", "", "ALGER"),
    ("00894", "SEGUENI MOHAMMED", "SEGUENI MOHAMMED", "Azeffoun centre, Cne de Azeffoun", "026 25 00 70", "TIZI OUZOU"),
    ("00896", "BOUDJAOUI SAID", "EURL RAHMANI PROMOTION IMMOBILIERE",
     "Local N°01 Rue Metiche Mohamed Arab, Cne de Boghni", "026 28 45 76", "TIZI OUZOU"),
    ("00897", "NAAS OMAR", "SARL CIRIME BITIME",
     "Cité 420 logts Bt 24 N° 04 Ilot de propriété N° 97 section 02, El Hamiz, Dar El Beida", "023 86 51 47", "ALGER"),
    ("00898", "ARAB TAYEB", "ARAB TAYEB", "Coopérative El Falah N° 04, Route Ain Kesma", "046 21 52 61", "TIARET"),
    ("00899", "MESRI EL HACHEMI", "MESRI EL HACHEMI", "19 Route Frigo Bt03 N°153, Cne de Tiaret", "040 81 18 68",
     "TIARET"),
    ("00900", "BENAMIRA ISLAM", "SARL NEO VRAIGNE",
     "Route de l'observatoire N° 11 (Coopérative El Omran), Cne de Bouzareah", "021 60 12 73", "ALGER"),
    ("00902", "MIMOU KHEIR EDDINE", "EURL BRAHIM SALEM TRAVAUX PUBLICS", "Cité Essanouabar N°97, Cne de Aïn El Turk",
     "041 58 34 99", "ORAN"),
    ("00903", "BAOUCHE DERRADJI", "BAOUCHE DERRADJI", "Rue 20 Août 1955 Oued Endja, Cne de Ahmed Rachedi", "", "MILA"),
    ("00904", "HAMOUDA ABDELHALIM", "HAMOUDA ABDELHALIM", "Cité Elkmounia Rez de chaussée, Cne de Mila", "", "MILA"),
    ("00905", "TOUMI SALAH EDDINE", "EURL MJS HTT PROMOTION IMMOBILIERE",
     "Rue Mustapha Ouali El Said Bt N°28, Cne de Alger-Centre", "021 71 95 28", "ALGER"),
    ("00906", "BOUKRISSA ADEL", "SARL BOUKRISSA PROMOTION IMMOBILIERE",
     "Cité El Yassamine 50 logts Bt B Section 01, Cne de Bir El Djir", "021 35 10 77", "ORAN"),
    ("00907", "ATTAF OUAHID", "SARL SAPIMM", "16 Rue des trois martyrs, Cne de Tessala El Merdja", "021 40 03 31",
     "ALGER"),
    ("00908", "BOUKHEDIR ZOUBIR", "SARL BOUKHEDIR", "Lot Amir Abdelkader Local N°16, Cne de Azzaba", "038 93 48 42",
     "SKIKDA"),
    ("00909", "LAFIOUNE SALAH", "SARL LEGODART", "Cité les Dunes section 04 N°363, Cne de Chéraga", "021 36 95 69",
     "ALGER"),
    ("00910", "ABERKANE YACINE", "ABERKANE YACINE",
     "Local N°08 Centre Commercial Barche 08 Rue Fredj Abdelaziz1er étage, Cne de Tizi Ouzou", "026 40 70 13",
     "TIZI OUZOU"),
    ("00912", "DAHOU MIRI", "SARL EL MIRI DAHOU", "Cité Said Hamdine 195/574 Logts Bt 34 N°01, Cne de Bir Mourad Raïs",
     "021 60 94 76", "ALGER"),
    ("00913", "HADJI AOMAR", "SARL ETUDES ET REALISATIONS", "Cité des complexes Bt E N°20, Cne de Relizane",
     "046 92 43 97", "RELIZANE"),
    ("00915", "AIT SAHNOUNE HAMID", "AIT SAHNOUNE HAMID",
     "Résidence Coopérative Tahar Jaout N° 202 Local 01 rez de chaussée, Nouvelle Ville, Cne de Tizi Ouzou", "",
     "TIZI OUZOU"),
    ("00916", "SEDDIK AHMED", "EURL ENG REAL", "N°20 Rue Rehla Teyeb Local N°02, Cne de Tiaret", "021 68 76 05",
     "TIARET"),
    ("00918", "BOUACHEMA SAID", "SARL SAMA MOSTA", "Bt B 03 N° 20, Hai Nassim El Bahr, Zegheloul, Cne de Mostaganem",
     "", "MOSTAGANEM"),
    ("00920", "BENTORKI MOHAMED HAKIM", "EURL BMH PROMO", "Place Mars N°12 Lotissement 42 Lots, Cne de Annaba",
     "038 43 14 75", "ANNABA"),
    ("00921", "SADOK SMAIL", "SARL SAINT AUGUSTIN COOPERATIVE IMMOBILIERE",
     "N°05, Route de Dely Ibrahim, Cne de Chéraga", "", "ALGER"),
    ("00925", "FETOUH ABDELHAKIM", "EURL FETTOUH PROMOTION IMMOBILIERE",
     "Cité X Lotissement Zemouri selsabil N°138 parc à fourrage, Cne de Batna", "033 85 22 97", "BATNA"),
    ("00926", "DENDANI KHADIDJA", "DENDANI KHADIDJA",
     "Quartier de Martyr Yahiaoui Said Villa A N°124 RDC, Cne de Boumerdes", "", "BOUMERDES"),
    ("00927", "YAHI HACENE", "SPA BATIMETAL IMMOBILIERE",
     "Résidence Mimosas 92 Logts Local N°02 Taher Bouchet Lotissement Semmar, Cne de Birkhadem", "023 59 70 49",
     "ALGER"),
    ("00928", "CHIBANI AFIF", "EURL EDIMBAT",
     "Résidence Les Amendiers, Lot N° 137 Houche Loukil Bt A Local N°03, Cne de Baba Hassen", "023 57 97 29", "ALGER"),
    ("00929", "TAHRAOUI AHMED AMINE", "SARL STAM PROMOTION IMMOBILIERE",
     "Centre commercial El Mountazah Harouni Bouziane 2 étage, Cne de Oran", "041 50 23 65", "ORAN"),
    ("00930", "BOURAS SEDDIK", "BOURAS SEDDIK", "Cité 40 logts local N° 01, Cne de Ouled Addi Guebala", "035 55 19 48",
     "M SILA"),
    ("00931", "SMAIL NADJIB", "SMAIL NADJIB", "Hai El Bassatine la Verdure avenue Aissat Idir, Cne de Batna",
     "033 25 34 90", "BATNA"),
    ("00932", "IAMRANENE HAKIM", "SARL IAMRANENE BOGHNI PROMOTION",
     "Local N° 01 Tala Brahim Beni Mendas, Cne de Boghni", "026 28 43 37", "TIZI OUZOU"),
    ("00933", "BENMERZOUG RAMDANE", "BENMERZOUG RAMDANE",
     "Boulevard Houari Boumediene, rue Righi Said Section 56 groupe de propriété 176 bureau N°03, Cne de Bordj Bou Arreridj",
     "035 73 01 75", "B.B.ARRERIDJ"),
    ("00934", "BATATA ABDELHAMID", "BATATA ABDELHAMID", "1er Mai HLM groupe 08 BT A N°03, Cne de Sidi M'Hamed",
     "021 66 52 89", "ALGER"),
    ("00935", "BOUSNINA MOSTEFA", "SARL BOUSNINA ET METAI",
     "Promotion immobilère Khanfri 56 logts avenue 02 secteur B Bt N°14, Cne de Sétif", "036 51 95 95", "SETIF"),
    ("00936", "CHEKILAH LAKHDAR", "EURL CHEKILAH PROMOTION IMMOBILIERE",
     "Lotissement 282 lots portant le N°180 Ilot 17, Cne de Aïn Arnat", "036 73 13 08", "SETIF"),
    ("00937", "CHERGUI SLIMANE", "CHERGUI SLIMANE", "Cité 250 logts N°03, Cne de Salah Bey", "036 67 90 75", "SETIF"),
    ("00938", "SOLTANI FATEH", "SNC GROUPE SOLTANI ET CIE PROMOTION IMMOBILIERE",
     "Promotion immobilière 56 logts et 51 locaux, Cne de Aïn Oulmene", "036 58 11 28", "SETIF"),
    ("00939", "BOUCHERAI DJAMEL", "SNC BOUCHERAI FRERES", "Quartier Douck Sidi Aich, Cne de Sidi-Aïch", "034 29 62 97",
     "BEJAIA"),
    ("00940", "DOUAG ABDESLEM", "DOUAG ABDESLEM", "Cité El Hedhab Bt 02 N°07 Rez de chausée, Cne de Sétif", "",
     "SETIF"),
    ("00943", "ZITOUNI ADDA MOULAY DRISS", "EURL BELEDIFICE PROMOTION",
     "Résidence El Yasmine Bloc D N°21, Cne de Mostaganem", "045 30 97 13", "MOSTAGANEM"),
    ("00944", "TAZEGAIT MILOUD", "EURL ETPBH TAZEGAIT MILOUD", "Lieu Dit Esplanade Solidarité, Cne de Chlef",
     "027 77 41 25", "CHLEF"),
    ("00946", "SETTAR RAFIK", "SETTAR RAFIK", "La Grande Baie cité Toubal Local N°30 1er étage, Cne de Béjaïa",
     "034 10 93 84", "BEJAIA"),
    ("00947", "KEBBICHE RACHID", "KEBBICHE RACHID", "Local N°02 lieu dit Bouhia, Cne de Seddouk", "034 10 24 47",
     "BEJAIA"),
    ("00948", "AYARI MUSTAPHA", "AYARI MUSTAPHA",
     "Route de Zaarouria 30 logts LSP N°01 Bt 13 Escalier 01 RDC, Cne de Souk Ahras", "", "SOUK AHRAS"),
    ("00949", "BEKTACHE SAOU", "SARL BBK PROMOTION", "Résidence la grande Baie, cité Tobal 2ème étage, Cne de Béjaïa",
     "034 10 93 32", "BEJAIA"),
    ("00950", "KERBOUA ZOHRA", "EURL KERBOUA ZOHRA",
     "Zone Djebel El Wahch, résidence Lazri Djenar N° A15, Bt B1 N°02, Cne de El Khroub", "031 62 28 73",
     "CONSTANTINE"),
    ("00952", "HED MESSAOUD AIMAD", "HED MESSAOUD AIMAD",
     "Local 18 Par R 263 Tranche 50 Logement Part Et 20 Locaux, Cne de Ferdjioua", "031 59 80 37", "MILA"),
    ("00954", "SOUALMIA RAOUF", "SOUALMIA RAOUF", "Quatre chemins local B Ain El Bey, Cne de El Khroub", "031 59 80 37",
     "CONSTANTINE"),
    ("00955", "BOUAFIA FAYCAL", "SNC FRERES BOUAFIA LAYANNE PROMOTION IMMOBILIERE",
     "Cité 11 Décembre 1961 route Djebel El Ouahch N°16 A, Cne de Constantine", "031 72 37 15", "CONSTANTINE"),
    ("00956", "BOUKHEZAR ABDERRAOUF", "SARL OSCAR PROMOTION IMMOBILIERE",
     "Boulevard Pasteur, Belle Vue N°58, Cne de Constantine", "031 92 09 20", "CONSTANTINE"),
    ("00957", "BELHI HACENE", "BELHI HACENE", "Cité Boudraa Salah Terrain Benchergui N°319, Cne de Constantine", "",
     "CONSTANTINE"),
    ("00958", "CHOUABIA MOHAMMED TAYEB", "CHOUABIA MOHAMMED TAYEB",
     "Lotissement N°02 (19 Juin 1965) Lot N°22, Cne de Sedrata", "037 37 76 96", "SOUK AHRAS"),
    ("00959", "TABNI IMAD", "TABNI IMAD", "Mafraza N° 02, Ramdane Djamel", "", "SKIKDA"),
    ("00960", "BOUABIBSA MOSTEFA", "BOUABIBSA MOSTEFA", "Cité des Martyrs N°48, Cne de Ben Mehidi", "038 69 21 53",
     "EL TARF"),
    ("00961", "DAHMA KOUIDER", "EURL KODA PROM", "Plateau Cité Saidani Allel N°02, Cne de Reghaïa", "", "ALGER"),
    ("00962", "DJELLI NACERA", "SARL PROMOTION IMMOBILIERE WAST ADDAR",
     "N°04 Boulevard Mahfoud Saad Allah, Cne de Bourouba", "021 26 25 71", "ALGER"),
    ("00965", "HARIDI MOUNIR", "SARL HARIDI OMAR PROMOTION IMMOBILIERE",
     "Lotissement Ain Defla 01 N°25 A, Cne de Guelma", "037 14 23 28", "GUELMA"),
    ("00966", "SAOUDI FARID", "SAOUDI FARID", "Lieu dit Zouzamane local N°01, Cne de M'Chedallah", "", "BOUIRA"),
    ("00967", "ZERROUALI MOHAMMED", "ZERROUALI MOHAMMED",
     "Rez de chaussée Bloc I N°04, Centre Ain Merane, Cne de Aïn Merane", "", "CHLEF"),
    ("00968", "KADDARI SLIMANE", "KADDARI SLIMANE", "N°04 Rue Ibrahim Hedjres Bt N°12 6ème étage, Cne de Beni Messous",
     "021 64 94 88", "ALGER"),
    ("00969", "MAKHLOUF SALIM", "MAKHLOUF SALIM", "Cité L'école, approche Zighoud Youcef N°21, Cne de Guelma", "",
     "GUELMA"),
    ("00970", "ZAGHDOUDI ABDERRAHMENE", "ZAGHDOUDI ABDERRAHMENE", "Cite 19 Juin Lots 02 N° 405, Cne de Guelma", "",
     "GUELMA"),
    ("00971", "MEZIANE ABDELHAKIM", "EURL MEZIANE ABD EL HAKIM PROMOTION IMMOBILIERE",
     "Cité El Hadika N°58, Cne de Oum el Bouaghi", "032 56 73 72", "O.E.BOUAGHI"),
    ("00972", "GUERMID SEDDAM", "EURL ETREPRISE EL IAMARE JMS PROMOTION IMMOBILIERE",
     "N°05, Lots Tlemçani Zabana, Cne de Blida", "025 20 16 61", "BLIDA"),
    ("00974", "BOUMOUS LAID", "BOUMOUS LAID", "Route d'Oran ZU 03 Cité 110 logts Bt 1 N°10, Cne de Mostaganem",
     "048 38 32 52", "MOSTAGANEM"),
    ("00975", "HEROUAL MOHAMED", "HEROUAL MOHAMED",
     "Lot 158 tranche lotissement sociale Eltofah N° 03 Route Ain Bouchekif N°1042, Cne de Tiaret", "", "TIARET"),
    ("00977", "MAIFIA ABDELHAK", "MAIFIA ABDELHAK", "N°06 Rue Brahmia Abdallah, Cne de Djeballah Khemissi", "",
     "GUELMA"),
    ("00978", "AOUED MOHAMED RIDA", "AOUED MOHAMED RIDA",
     "Lotissement 02 Cité Bouglouf Mabrouk N°01 RDC, Cne de Ramdane Djamel", "", "SKIKDA"),
    ("00979", "EL FRANGI KHEDIDJA", "SARL B T K M",
     "Ilot 07 Bt 01 Hai Colonnel Lotfi Residence Wafaa Local 01, Cne de Oran", "041 28 53 11", "ORAN"),
    ("00980", "BALOUL ZAHER", "BALOUL ZAHER", "Village Terga Azemour ex Douar Medala, Cne de Béjaïa", "034 21 28 01",
     "BEJAIA"),
    ("00981", "TOUNSI MIMOUN", "SARL BATI LEADER TOUNSI", "Zone Industriel Lot N°04 Local B, Cne de Sidi Bel Abbes",
     "048 70 31 05", "S.B.ABBES"),
    ("00982", "CHABNI MOHAMED", "CHABNI MOHAMED",
     "Lotissement 241 logts, Hai Essabah Bt 15 RDC N°02, Cne de Sidi Chami", "041 72 05 28", "ORAN"),
    ("00983", "AZIZ MOHAMED MUSTAPHA", "AZIZ MOHAMED MUSTAPHA", "Rue Saint Jules cité Tafna N°01, Cne de Oran",
     "041 28 24 50", "ORAN"),
    ("00984", "KOUADRI MEBAREK", "KOUADRI MEBAREK", "Cité des Jardins, Cne de Aïn Azel", "036 55 78 01", "SETIF"),
    ("00985", "KHALLA NOUREDINE", "KHALLA NOUREDINE", "Cité El Hadj M'Barek N°48, Cne de Guelma", "", "GUELMA"),
    ("00987", "ELBEKRI LARBI", "ELBEKRI LARBI", "Cité Aouadi Kaddour Belkhir, Cne de Guelma", "", "GUELMA"),
    ("00988", "BOULAHFA KAMEL", "BOULAHFA KAMEL", "Cité 20 logts El Fedjoudj Local N°03, Cne de Guelma", "037 26 39 56",
     "GUELMA"),
    ("00990", "BOUHEMILA NADIR", "EURL PROMOTION IMMOBILIERE LYRIA",
     "Cite Rym 116 Logts N° 4 Cne De Annaba, Cne de Annaba", "038 86 13 27", "ANNABA"),
    ("00991", "NEHAL YACINE", "NEHAL YACINE", "Cité 80 logts 08 mars Bloc 2 N°10, Cne de Annaba", "", "ANNABA"),
    ("00993", "BENOUAR BOUCIF", "SARL BUILDING PROMOTION IMMOBILIERE",
     "Lieu dit SUF 04 Lot N°545 Section N°03 Bt A, Cne de Bir El Djir", "041 44 94 83", "ORAN"),
    ("00994", "TABITI ABDELKADER", "TABITI ABDELKADER",
     "Cité El Sadikia Cité des Fonctionnaires Bt A3 1er étage porte 312, Cne de Oran", "041 42 53 19", "ORAN"),
    ("00995", "AWGRFU ANNABA", "AWGRFU ANNABA", "Rue Mustapha Ben Boulaid N°10 Bis, Cne de Annaba", "038 86 53 42",
     "ANNABA"),
    ("00996", "TORCHE SAMIR", "TORCHE SAMIR", "Cité 64 LSP, Cne de Bordj Ghédir", "", "B.B.ARRERIDJ"),
    ("00998", "HABCHI NOUREDDINE", "EURL GENERAL IMMOBILIER", "Route de hamla, Cité 165 logts Bt C RDC, Cne de Batna",
     "033 25 32 60", "BATNA"),
    ("00999", "BABAHACENE ABDELHADI", "EURL HOLDING CONSTRUCTION",
     "Cité Esseddikia, Diar Maaraket Aflou 400 logts N°19 Appartement N°02, Cne de Oran", "", "ORAN"),
    ("01001", "YOUSFI ABDELMOUMEN", "YOUSFI ABDELMOUMEN", "Rue Yousfi Mahmoud N°10 RDC, Cne de Oum el Bouaghi",
     "032 56 52 82", "O.E.BOUAGHI"),
    ("01002", "AISSANI ATHMANE", "AISSANI ATHMANE",
     "Rue Thamchit K L a côté de route Biskra Bt B 06 N°05 2Em étage, Cne de Batna", "033 39 37 25", "BATNA"),
]

# ============================================================
# إضافة المطورين الجدد
# ============================================================
print("=" * 60)
print("🚀 بدء إضافة المطورين الجدد...")
print("=" * 60)

created = 0
exists = 0
errors = 0

for data in new_promoteurs:
    num, nom, gerant, adresse, tel, wilaya_name = data
    wilaya = wilaya_map.get(wilaya_name)

    if not wilaya:
        errors += 1
        if errors <= 10:
            print(f"⚠️ تخطي: ولاية غير معروفة '{wilaya_name}' للمطور {num}")
        continue

    if not PromoteurImmobilier.objects.filter(numero_affiliation=num).exists():
        try:
            PromoteurImmobilier.objects.create(
                numero_affiliation=num,
                nom_entreprise=nom[:255] if nom else "",
                nom_gerant=gerant[:255] if gerant else "",
                adresse=adresse[:500] if adresse else "",
                telephone=tel[:50] if tel else "",
                wilaya=wilaya,
            )
            created += 1
            if created % 50 == 0:
                print(f"📊 تم إضافة {created} مطور...")
        except Exception as e:
            errors += 1
            print(f"❌ خطأ في إضافة المطور {num}: {e}")
    else:
        exists += 1

print("=" * 60)
print("📊 النتائج النهائية:")
print(f"   ✅ تم إضافة {created} مطور جديد")
print(f"   ⚠️ موجود مسبقاً: {exists} مطور")
print(f"   ❌ أخطاء/تخطي: {errors} سجل")
print(f"   📈 إجمالي المطورين الآن: {PromoteurImmobilier.objects.count()}")
print("=" * 60)