# Generated by Django 6.0.4 on 2026-05-31 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=100, verbose_name='الاسم بالفرنسية')),
            ],
            options={
                'verbose_name': 'بلدية',
                'verbose_name_plural': 'البلديات',
                'ordering': ['wilaya__code', 'name_fr'],
            },
        ),
        migrations.CreateModel(
            name='NatureImmeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('individuels', 'Individuels | أفراد'), ('collectifs', 'Collectifs et Semi-Collectifs | جماعية وشبه جماعية'), ('locaux_commerciaux', 'Locaux Commerciaux & Usage Professionnel | محلات تجارية ومهنية'), ('hangars', 'Hangars | مستودعات'), ('terrains_nus', 'Terrains Nus | أراضي عارية'), ('terrains_plaine', 'Terrains Agricoles en Plaine | أراضي زراعية سهلية'), ('terrains_pente', 'Terrains Agricoles en Pente | أراضي زراعية منحدرة')], max_length=30, unique=True, verbose_name='المفتاح')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=150, verbose_name='الاسم بالفرنسية')),
            ],
            options={
                'verbose_name': 'طبيعة العقار',
                'verbose_name_plural': 'طبائع العقارات',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=100, verbose_name='الاسم بالفرنسية')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('residential', 'Zone résidentielle | المنطقة السكنية'), ('city_center', 'Centre-ville | وسط المدينة'), ('peripheral', 'Zone périphérique | المنطقة المحيطية'), ('remote', "Zone d'éloignement | المنطقة النائية")], max_length=20, unique=True, verbose_name='المفتاح')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=100, verbose_name='الاسم بالفرنسية')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='properties.category')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('standing', 'Standing | ستاندينغ'), ('ameliore', 'Amélioré | محسّن'), ('economique', 'Economique | اقتصادي'), ('precaire', 'Précaire | هش'), ('artere_haute', 'Artère hautement commerciale | شارع تجاري مرتفع'), ('artere_moyen', 'Artère moyennement commerciale | شارع تجاري متوسط'), ('artere_faible', 'Artère peu commerciale | شارع تجاري ضعيف'), ('zone_urbaine', 'Situé en zone urbaine | في منطقة حضرية'), ('zone_rurale', 'Situé en zone rurale | في منطقة ريفية'), ('pp_2f_avec', 'Pleine propriété 2 façades avec raccordements | ملكية تامة 2 واجهة مع توصيلات'), ('pp_1f_avec', 'Pleine propriété 1 façade avec raccordements | ملكية تامة 1 واجهة مع توصيلات'), ('pp_2f_sans', 'Pleine propriété 2 façades sans raccordements | ملكية تامة 2 واجهة بدون توصيلات'), ('pp_1f_sans', 'Pleine propriété 1 façade sans raccordements | ملكية تامة 1 واجهة بدون توصيلات'), ('indivision', "Dans l'indivision | في الشياع"), ('industriel', 'Industriel | صناعي'), ('potentialite_elevee', 'Potentialité élevée | إمكانية عالية'), ('potentialite_moyenne', 'Potentialité moyenne | إمكانية متوسطة'), ('potentialite_faible', 'Potentialité faible | إمكانية ضعيفة')], max_length=30, verbose_name='المفتاح')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=200, verbose_name='الاسم بالفرنسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='properties.natureimmeuble', verbose_name='طبيعة العقار')),
            ],
            options={
                'verbose_name': 'خاصية',
                'verbose_name_plural': 'الخصائص',
                'ordering': ['nature', 'order'],
                'unique_together': {('nature', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('area_sqm', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='المساحة (م²)')),
                ('bedrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الحمامات')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('house', 'منزل'), ('villa', 'فيلا'), ('land', 'أرض'), ('commercial', 'محل تجاري'), ('office', 'مكتب'), ('shop', 'متجر'), ('warehouse', 'مستودع')], max_length=20, verbose_name='نوع العقار')),
                ('listing_type', models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار'), ('exchange', 'للبدل')], max_length=10, verbose_name='نوع العملية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('cpc', models.DecimalField(decimal_places=2, default=0.2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPC')),
                ('is_cpc_active', models.BooleanField(default=False, verbose_name='CPC نشط')),
                ('cpc_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ميزانية CPC')),
                ('cpc_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المصروف من CPC')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accounts.agentprofile', verbose_name='الوكيل')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.category', verbose_name='الفئة')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.commune', verbose_name='البلدية')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.wilaya', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, verbose_name='معرف الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترجع')], default='pending', max_length=50, verbose_name='الحالة')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='رقم المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='properties.wilaya', verbose_name='الولاية'),
        ),
        migrations.CreateModel(
            name='ValuationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى (دج/م²)')),
                ('max_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأقصى (دج/م²)')),
                ('reference_year', models.IntegerField(default=2024, verbose_name='سنة المرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('caracteristique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.caracteristique', verbose_name='الخاصية')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.commune', verbose_name='البلدية')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.natureimmeuble', verbose_name='طبيعة العقار')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.wilaya', verbose_name='الولاية')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.zone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'نطاق تقييم',
                'verbose_name_plural': 'نطاقات التقييم',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['wilaya', 'commune'], name='properties__wilaya__e246bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'listing_type'], name='properties__propert_6ab6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price', 'area_sqm'], name='properties__price_9d726b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'is_featured'], name='properties__is_acti_ff7ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationrange',
            index=models.Index(fields=['wilaya', 'commune'], name='properties__wilaya__89a6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationrange',
            index=models.Index(fields=['zone', 'nature'], name='properties__zone_id_1bfd61_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationrange',
            index=models.Index(fields=['is_active'], name='properties__is_acti_caaae3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valuationrange',
            unique_together={('wilaya', 'commune', 'zone', 'nature', 'caracteristique')},
        ),
    ]
