# Generated by Django 6.0.4 on 2026-05-31 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoteurImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_affiliation', models.CharField(max_length=10, unique=True, verbose_name='رقم الانتساب')),
                ('numero_agrement', models.CharField(blank=True, max_length=20, verbose_name='رقم الاعتماد')),
                ('numero_tnpi', models.CharField(blank=True, max_length=50, verbose_name='رقم التسجيل TNPI')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('nom_gerant', models.CharField(blank=True, max_length=255, verbose_name='اسم المسير')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان التجاري')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.wilaya', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'مطور عقاري',
                'verbose_name_plural': 'المطورين العقاريين',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='ProjetImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('localisation', models.TextField(verbose_name='الموقع')),
                ('daira', models.CharField(blank=True, max_length=100, verbose_name='الدائرة')),
                ('date_garantie', models.DateField(blank=True, null=True, verbose_name='تاريخ منح الضمان')),
                ('total_logements', models.IntegerField(default=0, verbose_name='إجمالي الوحدات')),
                ('f1_count', models.IntegerField(default=0, verbose_name='عدد F1')),
                ('f2_count', models.IntegerField(default=0, verbose_name='عدد F2')),
                ('f3_count', models.IntegerField(default=0, verbose_name='عدد F3')),
                ('f4_count', models.IntegerField(default=0, verbose_name='عدد F4')),
                ('f5_count', models.IntegerField(default=0, verbose_name='عدد F5')),
                ('f6_count', models.IntegerField(default=0, verbose_name='عدد F6')),
                ('duplex_count', models.IntegerField(default=0, verbose_name='عدد Duplex')),
                ('triplex_count', models.IntegerField(default=0, verbose_name='عدد Triplex')),
                ('villa_count', models.IntegerField(default=0, verbose_name='عدد Villas')),
                ('cave_count', models.IntegerField(default=0, verbose_name='عدد Caves')),
                ('garage_count', models.IntegerField(default=0, verbose_name='عدد Garages')),
                ('parking_count', models.IntegerField(default=0, verbose_name='عدد Parkings')),
                ('local_count', models.IntegerField(default=0, verbose_name='عدد Locaux commerciaux')),
                ('description', models.TextField(blank=True, verbose_name='وصف المشروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.commune', verbose_name='البلدية')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.wilaya', verbose_name='الولاية')),
                ('promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='properties.promoteurimmobilier', verbose_name='المطور')),
            ],
            options={
                'verbose_name': 'مشروع عقاري',
                'verbose_name_plural': 'المشاريع العقارية',
                'ordering': ['-date_garantie', 'nom_projet'],
            },
        ),
        migrations.AddIndex(
            model_name='promoteurimmobilier',
            index=models.Index(fields=['numero_affiliation'], name='properties__numero__8a6763_idx'),
        ),
        migrations.AddIndex(
            model_name='promoteurimmobilier',
            index=models.Index(fields=['wilaya'], name='properties__wilaya__cd85be_idx'),
        ),
        migrations.AddIndex(
            model_name='projetimmobilier',
            index=models.Index(fields=['promoteur', 'wilaya'], name='properties__promote_b08dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='projetimmobilier',
            index=models.Index(fields=['date_garantie'], name='properties__date_ga_80465d_idx'),
        ),
    ]
