# Generated by Django 6.0.4 on 2026-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_promoteurimmobilier_projetimmobilier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoteurimmobilier',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='promoteurs/avatars/%Y/%m/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='promoteurimmobilier',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='promoteurs/covers/%Y/%m/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='promoteurimmobilier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='promoteurs/logos/%Y/%m/', verbose_name='شعار الشركة'),
        ),
    ]
