# Generated by Django 6.0.4 on 2026-05-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المعلن',
                'verbose_name_plural': 'ملفات المعلنين',
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default='0Rg3H_RT9ei4bIbjmnQQlg', max_length=100, unique=True)),
                ('clicks_count', models.IntegerField(default=0)),
                ('valid_clicks_count', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='properties.property')),
            ],
            options={
                'verbose_name': 'رابط ترويجي',
                'verbose_name_plural': 'روابط ترويجية',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='rewards.affiliatelink')),
            ],
            options={
                'verbose_name': 'نقرة',
                'verbose_name_plural': 'النقرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('valid_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المروج',
                'verbose_name_plural': 'ملفات المروجين',
            },
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='rewards.promoterprofile'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='عدد النقاط')),
                ('reason', models.CharField(max_length=200, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط المستبدلة')),
                ('reward_type', models.CharField(choices=[('cash', 'نقود'), ('discount', 'خصم'), ('gift', 'هدية'), ('voucher', 'قسيمة شراء')], max_length=20, verbose_name='نوع المكافأة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استبدال مكافأة',
                'verbose_name_plural': 'استبدال المكافآت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('promoter', 'property')},
        ),
    ]
